/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExpressRouteImport } from './routes/express'
import { Route as IndexRouteImport } from './routes/index'

const ExpressRoute = ExpressRouteImport.update({
  id: '/express',
  path: '/express',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/express': typeof ExpressRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/express': typeof ExpressRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/express': typeof ExpressRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/express'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/express'
  id: '__root__' | '/' | '/express'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExpressRoute: typeof ExpressRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/express': {
      id: '/express'
      path: '/express'
      fullPath: '/express'
      preLoaderRoute: typeof ExpressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExpressRoute: ExpressRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
